services:
  auto-confirmation:
    build: .
    container_name: auto_confirmation_xbox_consumer
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Монтируем весь проект целиком
      - .:/app
